'''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

MAX = 4000000

def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return(fibonacci(n-1)+fibonacci(n-2))
    

i, value, x = MAX, 0, 0
for num in range(0, i):
    value = fibonacci(num)
    if value % 2 == 0:
        x += value
    elif x > MAX:
        print(x)
        break